AC_Training/auhuberp/AcTraining/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AcTraining.Models;

namespace AcTraining.Controllers
{
	public class HomeController : Controller
	{
		private readonly ICustomerRepository rep;

		public HomeController(ICustomerRepository rep)
		{
			this.rep = rep;
			//this.rep.CreateCustomer(new Customer(){FirstName = "Test"});
			//this.rep.CreateCustomer(new Customer() { FirstName = DateTime.Now.ToLongDateString() });
		}

		public ActionResult Index()
		{
			ViewBag.Title = "Home Page";

			return View(model: "TestText");
		}
		public ActionResult Test()
		{
			var customer = rep.GetCustomer(1);
			return View(customer);

		}

		public ActionResult Grid()
		{
			return View();
		}
		public ActionResult LineChart()
		{
			return View();
		}

		public ActionResult Knockout()
		{
			return View();
		}
	}
}

AC_Training/auhuberp/AcTraining/Controllers/ResetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web.Http;
using AcTraining.Models;
using AutoPoco;
using AutoPoco.DataSources;
using AutoPoco.Engine;

namespace AcTraining.Controllers
{
	// Fehlende Nuget Pakete:  
	// PM> Install-Package AutoPocoBeta
	// PM> Install-Package AutoPoco.DataSources
	public class ResetController : ApiController
	{
		private readonly DataContext db;

		public ResetController(DataContext db)
		{
			this.db = db;
		}

		public HttpResponseMessage Get()
		{
			var demoData = GenerateDemoCustomers();

			db.Customers.RemoveRange(db.Customers.Select(c => c));
			db.Customers.AddRange(demoData);

			db.SaveChanges();

			// Beispiel, damit IE nicht auf die Idee kommt, XML-Datei runterzuladen - nicht nötig bei Firefox
			var response = new HttpResponseMessage(HttpStatusCode.OK)

				{
					Content = new StringContent("Demo Data was resetted!")
				};
			response.Content.Headers.ContentType = new MediaTypeHeaderValue("text/plain");
			return response;

			//return Request.CreateResponse(HttpStatusCode.OK, "Demo Data was resetted!");
		}

		private static IEnumerable<Customer> GenerateDemoCustomers()
		{
			IGenerationSessionFactory factory = AutoPocoContainer.Configure(x =>
			{
				x.Conventions(c => c.UseDefaultConventions());
				x.AddFromAssemblyContainingType<Customer>();

				Random rnd = new Random();

				x.Include<Customer>()
						.Setup(c => c.FirstName).Use<FirstNameSource>()
						.Setup(c => c.LastName).Use<LastNameSource>()
						.Setup(c => c.Mail).Use<EmailAddressSource>()
					//.Setup(c => c.DateOfBirth).Use<DateOfBirthSource>()
						.Setup(c => c.AmountOfOrders).Use<IntegerSource>(1, 100)
						.Setup(c => c.AmountOfInvoices).Use<SecondIntegerSource>(1, 100)
						;
			});

			IGenerationSession session = factory.CreateSession();
			return session.List<Customer>(100).Get();
		}


		public class SecondIntegerSource : DatasourceBase<int>
		{
			private readonly int _min;
			private readonly int _max;
			private static readonly Random _random = new Random((int)DateTime.Now.Ticks);

			public SecondIntegerSource()
			{
				_min = int.MinValue;
				_max = int.MaxValue;
			}

			public SecondIntegerSource(int min, int max)
			{
				_min = min;
				_max = max;
			}

			public override int Next(IGenerationContext context)
			{
				return _random.Next(_min, _max);
			}
		}
	}
}

AC_Training/auhuberp/AcTraining/Views/Home/Grid.cshtml
            <div id="grid"></div>

@section scripts
{
    <script>
        $(document).ready(function() {

            var dataSource = new kendo.data.DataSource(
                {
                    type: "odata",
                    transport: {
                        read: {
                            type: 'GET',
                            url: '/odata/Customers',
                            dataType: 'json'
                        }
                    },
                    schema: {
                        data: function(data) { return data.value; },
                        total: function(data) { return data['odata.count']; },
                        model: {
                            fields: {
                                Id: { type: "number" },
                                FirstName: { type: "string" },
                                LastName: { type: "string" },
                                Mail: { type: "string" },
                                AmountOfOrders: { type: "number" },
                                AmountOfInvoices: { type: "number" },
                                DateOfBirth: { type: "date" }
                            }
                        }
                    },
                    pageSize: 20,
                    serverPaging: true,
                    serverFiltering: true,
                    serverSorting: true
                }
            );
            $("#grid").kendoGrid({
                dataSource: dataSource,
                height:
                    550,
                filterable:
                    true,
                sortable:
                    true,
                pageable:
                    true,
                columns:
                [
                    { field: "Id" },
                    { field: "FirstName", title: "First Name" },
                    { field: "LastName", title: "Last Name" },
                    { field: "Mail" },
                    { field: "DateOfBirth", format: "{0:dd.MM.yyyy hh:mm}" }
                ]
            });
        });
    </script>
}

AC_Training/auhuberp/AcTraining/Views/Home/Index.cshtml
@model string
<div class="jumbotron">
    <h1>XXX!</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS, and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>

    @Html.ActionLink("Gehe zu Test", "Test", "Home", new {@class="btn btn-primary btn-lg"})
    @Html.ActionLink("Reset Data", "Reset", "api", null, new {@class="btn btn-warning btn-lg"})
    @Html.ActionLink("LineChart and Grid", "LineChart", "Home", new {@class="btn btn-warning btn-lg"})
    @Html.ActionLink("Gehe zu Knockout", "Knockout", "Home", new {@class="btn btn-danger btn-lg"})
</div>

@Html.Partial("Test", new Customer(){ FirstName = DateTime.Now.ToLongDateString() })

<br />
<a href="/odata/Customers?$top=5&$skip=2">Das ist Test top=5 - skip=2</a>

<br />
<button id="test" class="btn btn-warning btn-lg">Auto weg</button>

@section scripts
{
    <script>
        var myFirstModule = (function () {
            var _color = "red";

            var init = function () {
                $("#test").click(
                    function () {
                        $(this).css("color", _color);
                    });
            };
            var setColor = function (myColor) {
                _color = myColor;
            };

            return {
                init: init,
                setColor: setColor,
                
            };
        })();

        $(function () {
            // TODO: ich möchte hier die Farbe angeben können!
            var newColor = "green";
            myFirstModule.setColor(newColor);
            myFirstModule.init();
        });

    </script>
}

@section footer
{
<h1 style="color: greenyellow">@Model</h1>

}

AC_Training/auhuberp/AcTraining/Views/Home/Knockout.cshtml
@Html.ActionLink("Reset Data", "Reset", "api", null, new { @class = "btn btn-warning btn-lg", target="_blank" }) 

<div id="chat_template">
    
    <form class="form-horizontal">
        <h1>SignalR Chat</h1>
        <div class="form-group">
            <label class="col-sm-2 control-label">Name</label>
            <div class="col-sm-7">
                <input data-bind="textInput: name" type="text" class="form-control"></input>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Message</label>
            <div class="col-sm-7">
                <input data-bind="textInput: message" type="text" class="form-control"></input>
            </div>
        </div>
        <div class="form-group">
            <button id="btnSend" data-bind="click: sendMessage">Send!</button>
        </div>
        <ul class="form-group" data-bind="foreach: messages">
            <li>
                <b data-bind="    text: name"></b>:
                <span data-bind="    text: message"></span>
            </li>
        </ul>
    </form>
</div>

<div id="index_template">

    <h1 data-bind="text: header,
    style: { color: color }">Kundenn</h1>
    <input type="text" data-bind="textInput: header" />

    <h1 data-bind="style: { color: color }">:-)</h1>

    <button data-bind="click: setColor">Klick mich</button>

    <div data-bind="foreach: customers">

        <div class="panel panel-default pull-left col-md-5 " style="padding: 0; margin-right: 20px;">
            @*<img data-bind="src: IdGravatar" src="http://www.gravatar.com/avatar/1?d=wavatar&f=z" class="img-thumbnail pull-right" />*@
            <img data-bind="attr: { src: $root.getImage($data) }" class="img-thumbnail pull-right" />
            <div class="panel-heading" data-bind="    text: FirstName">Name</div>
            <div class="panel-body">

                <form class="form-horizontal">

                    <div class="form-group">

                        <label class="col-sm-2 control-label">#</label>
                        <div class="col-sm-7">
                            <input data-bind="textInput: Id" type="text" class="form-control">
                        </div>
                    </div>

                    <div class="form-group">

                        <label class="col-sm-2 control-label">FirstName</label>
                        <div class="col-sm-7">
                            <input data-bind="textInput: FirstName" type="text" class="form-control">
                        </div>
                    </div>

                    <div class="form-group">

                        <label class="col-sm-2 control-label">LastName</label>
                        <div class="col-sm-7">
                            <input data-bind="textInput: LastName" type="text" class="form-control">
                        </div>

                    </div>
                  
                    <button type="button" data-bind="click: $root.deleteCustomer" class="btn btn-danger" >
                        <i class="glyphicon glyphicon-trash"></i> Delete
                    </button>
                </form>
            </div>
        </div>
    </div>

    <pre data-bind="text: ko.toJSON($data, null, 2)"></pre>

</div>

<br style="clear: both;">
@section scripts {
    <script>
        var model = new CustomerViewModel();
        ko.applyBindings(model, $('#index_template').get(0));
        model.loadData();

        var chatModel = new ChatViewModel();
        ko.applyBindings(chatModel, $('#chat_template').get(0));
    </script>
};

AC_Training/auhuberp/AcTraining/Views/Home/LineChart.cshtml
<div id="chart"></div>
<div id="grid"></div>

@section scripts
{
    <script>

        function createChart() {

            var dataSource = new kendo.data.DataSource(
                   {
                       type: "odata",
                       transport: {
                           read: {
                               type: 'GET',
                               url: '/odata/Customers',
                               dataType: 'json'
                           }
                       },
                       schema: {
                           data: function (data) { return data.value; },
                           total: function (data) { return data['odata.count']; },
                           model: {
                               fields: {
                                   Id: { type: "number" },
                                   FirstName: { type: "string" },
                                   LastName: { type: "string" },
                                   Mail: { type: "string" },
                                   AmountOfOrders: { type: "number" },
                                   AmountOfInvoices: { type: "number" },
                                   DateOfBirth: { type: "date" }
                               }
                           }
                       },
                       pageSize: 20,
                       serverPaging: true,
                       serverFiltering: true,
                       serverSorting: true
                   }
               );

            $("#grid").kendoGrid({
                dataSource: dataSource,
                height:
                    550,
                filterable:
                    true,
                sortable:
                    true,
                pageable:
                    true,
                columns:
                [
                    { field: "Id" },
                    { field: "FirstName", title: "First Name" },
                    { field: "LastName", title: "Last Name" },
                    { field: "Mail" },
                    { field: "DateOfBirth", format: "{0:dd.MM.yyyy hh:mm}" }
                ]
            });
            $("#chart").kendoChart({
                dataSource: dataSource,
                title: {
                    text: "Spain electricity production (GWh)"
                },
                legend: {
                    position: "top"
                },
                seriesDefaults: {
                    type: "line"
                },
                series: [{
                    field: "AmountOfOrders",
                    name: "AmountOfOrders"
                }, {
                    field: "AmountOfInvoices",
                    name: "AmountOfInvoices"
                }],
                categoryAxis: {
                    field: "LastName",
                    labels: {
                        rotation: -90
                    },
                    crosshair: {
                        visible: true
                    }
                },
                valueAxis: {
                    labels: {
                        format: "N0"
                    },
                    majorUnit: 150
                },
                tooltip: {
                    visible: true,
                    shared: true,
                    format: "N0"
                }
            });
        }

        $(document).ready(createChart);
    </script>
}

AC_Training/auhuberp/AcTraining/Views/Home/Test.cshtml
<!--Alternative in web.config: <add namespace="AcTraining.Models">-->

@model AcTraining.Models.Customer
<h1>FirstName @Model.FirstName</h1>